name: site
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc
        version: 1.0
    - run: |
        mkdir site;
        FILES="wiki/*.md"
        for file in $FILES; do
          pandoc "$file" -o "site/`basename $file`.html"
          if ! test -e "site/`basename $file`.html"; then
            cp "$file" site/
            emacs -nw -q -L $dir "site/$file" --eval "(require 'wikipedia-mode)" \
              --eval "(require 'htmlize)" \
              --eval "(progn (wikipedia-mode) (htmlize-buffer))" \
              --eval "(progn (switch-to-buffer \"$file).html\")(write-file \"`basename $file`.html\"))" \
              --eval "(kill-emacs)"
          fi
        done
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/*
