name: site
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc
        version: 1.0
    - run: mkdir site; for file in *.md; pandoc "$file" -o "site/`basename ${file:0:-3}`.html"
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/*
