name: make
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
    - run: |
        FILES = $(wildcard wiki/*.md) $(wildcard wiki/*.mediawiki) $(wildcard wiki/*.textile)
        mkdir site;
        for file in wiki/*.md; do
          pandoc "$(file)" -o "site/`basename $file`.html"
          if ! test -e "site/`basename $file`.html"; then
            cp "$file" site/
            emacs -nw -q -L $dir "site/$file" --eval "(require 'wikipedia-mode)" \
              --eval "(require 'htmlize)" \
              --eval "(progn (wikipedia-mode) (htmlize-buffer))" \
              --eval "(progn (switch-to-buffer \"$file).html\")(write-file \"`basename $file`.html\"))" \
              --eval "(kill-emacs)"
          fi
        done
    - uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/*
